# Generated by Django 4.1.1 on 2022-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_location2_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='users/default.png', upload_to='profession'),
        ),
        migrations.AddField(
            model_name='product',
            name='lat',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lat2',
            field=models.FloatField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lon',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lon2',
            field=models.FloatField(blank=True, max_length=512, null=True),
        ),
    ]
