# Generated by Django 4.1.1 on 2022-10-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_product_location_category_image_product_lat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lat2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lon2',
        ),
        migrations.AlterField(
            model_name='product',
            name='lat',
            field=models.FloatField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lon',
            field=models.FloatField(blank=True, max_length=512, null=True),
        ),
    ]
