# Generated by Django 4.1.1 on 2022-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_category_city_remove_product_lat2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='closed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
