# Generated by Django 4.1.1 on 2022-10-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_product_closed_product_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='profession'),
        ),
    ]
