# Generated by Django 4.1.1 on 2022-10-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='city',
        ),
    ]
