# Generated by Django 4.1.1 on 2022-10-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_city_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='page.city'),
        ),
    ]
