# Generated by Django 4.1.1 on 2022-10-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_city_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
