# Generated by Django 4.1.1 on 2022-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.CharField(blank=True, max_length=5024, null=True),
        ),
    ]
